# .github/workflows/dotnet.yml
name: .NET Build & Run Check

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run (Smoke Test)
        run: |
          dotnet run --no-build &
          APP_PID=$!
          sleep 10
          kill $APP_PID || true
